channels:
 - bioconda
 - conda-forge
 - defaults
 - r
 - psi4

dependencies:
 - r-base
 - rstudio
 - bioconductor-biomart
 - bioconductor-fgsea
 - bioconductor-phyloseq
 - bioconductor-sva
 - bioconductor-batchelor
 - r-xcell
 - r-biocmanager
 - r-rann
 - r-rcolorbrewer
 - r-igraph
 - r-pheatmap
 - r-rcolorbrewer
 - r-scales
 - r-rafalib
 - r-readxl
 - r-enrichR
 - r-factoextra
 - r-rmarkdown
 - r-xlsx
 - r-keras
 - r-caret
 - compilers
 - scanorama
 - pip
 - pip:
   - umap-learn
   - leidenalg
   - mofapy2
   - tensorflow
   - keras
