---
title: "`r params$project_title`"
editor_options:
  chunk_output_type: console
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: yes
  html_document:
    code_folding: hide
    toc: yes
    toc_float:
      collapsed: no
params:
  organisation: Karolinska Institutet
  pi_mail: prin.cipal@ki.se
  pi_name: Prin Cipal
  project_title: Broliden_5325
  redmine_issue: '#5325'
  requester_mail: kristina.broliden@ki.se
  requester_name: Kristina Broliden
  staff_mail: supp.ortstaff@nbis.se
  staff_name: Supp Ortstaff
  staff_web: https://nbis.se/about/staff/supp-ortstaff/
---

```{r Setup, echo = FALSE}
knitr::opts_chunk$set(fig.width  = 10,
                      results    = "hold",
                      message    = FALSE,
                      warning    = FALSE)
```

#Load libraries and other scripts

```{r, echo = FALSE}
library(phyloseq)
library(circlize)
library(igraph)
library(rafalib)
library(umap)
source("~/repos/niceRplots/R/plotting_functions.R")
source("~/repos/niceRplots/R/add_fig_label.R")
source("~/repos/niceRplots/R/helper_functions.R")

```

#Defining some variables for the analysis

```{r, echo = FALSE}
PATH <- "~/Downloads/" #Path to the data

#color palettes
pal <- RColorBrewer::brewer.pal(8,"Set1") #color pallete for plots
heat_pal <- c("#000000", colorRampPalette(c("#000000","grey5","grey30","orange3","yellow","yellow","white"))(90))
cor_pal <- colorRampPalette(c("navy","white","firebrick"))(90)
```

# Loading data and metadata

```{r, echo = FALSE}
# Load metadata
metadata <- read.csv(paste0(PATH,"Clinical_visit_2_3.csv"))
rownames(metadata) <- as.character(metadata$PatID)

# Load datasets
datasets <- lapply(c("phyloseq_Tv3.RDS",
                     "phyloseq_CVLv2.RDS",
                     "phyloseq_CVLv3.RDS"),
                   function(x){ readRDS( paste0(PATH,x)) })
names(datasets) <- c("Tv3","CVLv2","CVLv3")
datasets <- datasets[-1] #in case you wanna test in 1 dataset

# Transform phyloseq data into normalized matricies ( log2[CP1K] )
datasets <- lapply(datasets,function(x){
    x <- as.data.frame(otu_table(x))
    colnames(x) <- as.character( sub( ".*u","",sub("[.Tv_].*","",colnames(x)) )  )
    x <- t(log2( t(x) / colSums(x) * 1000 + 1))
    x <- x[rowSums(x)>0,]
})

zscores <- lapply(datasets,function(x){
  zs <- t(apply(x,1,function(z) scale(z,T,T)))
  colnames(zs) <- colnames(x) ; rownames(zs) <- rownames(x)
  zs[zs > 6] <- 6
  zs[zs < -6] <- -6
  return(zs)
})
```


# Merging microbiome datasets

```{r, echo = FALSE}
mypar()
circos.heatmap.initialize(t(zscores[[1]]))

#cluster per dataset1
eucl <- as.matrix(dist(t(zscores[[1]]),method = "euclidean"))
h_bacs <- hclust(dist(zscores[[1]]),method = "ward.D2")
h_samples <- hclust(dist(t(zscores[[1]])),method = "ward.D2")

#plot dataset1
circos.heatmap(t(zscores[[1]][h_bacs$order,h_samples$order]), col = colorRamp2(seq(-2,6,length.out = 7),c("#000000","grey5","grey30","orange3","yellow","yellow","white")))

#plot dataset2
circos.heatmap(t(zscores[[2]][h_bacs$order,h_samples$order]), col = colorRamp2(seq(-2,6,length.out = 7),c("#000000","grey5","grey30","orange3","yellow","yellow","white")),
               rownames.side = "outside")
circos.clear()

```











#
