## conda requirements for all packages needed to run the analysis of the paper
# install with:  mamba env create -n tissue_adherent_VMB -f environment_tissue_adherent_VMB.yml
# then run: source activate tissue_adherent_VMB
name: tissue_adherent_VMB

channels:
 - bioconda
 - conda-forge
 - defaults
 - r

dependencies:
### R BIOCONDUCTOR PACKAGES ##
  - bioconductor-shortread=1.44.0
  - bioconductor-phyloseq=1.30.0
  - bioconductor-biostrings=2.54.0
  - bioconductor-dada2=1.14.0
  - bioconductor-edger=3.28.0
  - bioconductor-fgsea=1.12.0
### R CRAN PACKAGES ###
  - r-base=3.6.3
  - r-rmarkdown=2.*
  - r-shiny=1.6.0
  - r-openxlsx=4.2.3
  - r-phangorn=2.7.0
  - r-ips=0.0.11
  - r-tidyverse=1.2.1
  - r-igraph=1.2.6
  - r-rafalib=1.0.0
  - r-scales=1.1.1
  - r-rann=2.6.1
  - r-rcolorbrewer=1.1_2
  - r-readxl=1.3.1
  - r-enrichr=1.0
  - r-remotes=2.2.0
  - r-magick=2.6.0
  - r-uwot=0.1.10
  - r-rstatix=0.6.0
  - r-ggpubr=0.4.0
### GENERAL LIBRARIES ###
  - imagemagick=7.0.10_28
  

# Manual installation of packages that are not in conda:
# remotes::install_github("czarnewski/niceRplots",force=T)
