---
title: "Suppl. Figure 1. Bacterial abundance across datasets"
geometry: "left=2cm,right=2cm,top=2cm,bottom=2cm"
header-includes: 
- \usepackage{float}
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, out_dir, ...) {
    source("../../code/knit_function.R");
    custom_knit(inputFile, "../../lab_book/SupplFigure1/", ...)
    })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.path="./Suppl.Figures/",
  fig.align = "center",
  fig.process = function(filename){
    new_filename <- stringr::str_remove(string = filename, 
                                        pattern = "-1")
    fs::file_move(path = filename, new_path = new_filename)
    ifelse(fs::file_exists(new_filename), new_filename, filename)
})
# setwd("/Users/vilkal/work/Brolidens_work/Projects/broliden_5325/reports/manuscript")
```

```{r Load data, message=FALSE, warning=FALSE}
##################
# LOAD LIBRARIES #
##################
suppressWarnings({suppressMessages({suppressPackageStartupMessages({
  #remotes::install_github("czarnewski/niceRplots",force=T)
  library(niceRplots)
  library(tidyverse)
})  })  })

#############
# LODA DATA #
#############
datasets_all_samples <- readRDS("/Users/vilkal/work/Brolidens_work/Projects/Gabriella_repo/results/datasets_all_samples.RDS")
datasets_all_samples_ <- readRDS("../../results/03_normalize_data_output/datasets_all_samples.RDS")

#################
# COLOR PALETTS #
#################
Set1 <- c("#4DAF4A", "#377EB8", "#E41A1C", "#FF7F00", "#984EA3", "#FFFF33", "#A65628", "#F781BF", "#999999")
pal <- c(Set1,RColorBrewer::brewer.pal(8,"Set2"),
         RColorBrewer::brewer.pal(9,"Pastel1"),RColorBrewer::brewer.pal(8,"Pastel2")) #color pallete for plots
```

```{r Suppl.Fig.1 Bacterial_abundance, fig.asp=.5}
# test to get Paulos code to work with the new files who has less taxa due to filtering after normalization with only selected samples
# it does not currently work
# top_all_ <- lapply( datasets_all_samples_[1:2] , function(x){
#    sort(apply(x,1,var),decreasing = T)[1:20]} )
# top_ <- unique( sub( ".*[.]" , "" , names(unlist(top_all_)) ) )
# 
# x_ <- t(sapply(datasets_all_samples_[1:2],function(x){
#   c(t(x))
# }))
# colnames(x_) <- c(sapply(rownames(datasets_all_samples_[[1]]),
#                         function(i){rep(i,ncol(datasets_all_samples_[[1]]))}))
# rownames(datasets_all_samples_[[1]]) == rownames(datasets_all_samples_[[2]])

top_all <- lapply( datasets_all_samples[2:3] , function(x){
   sort(apply(x,1,var),decreasing = T)[1:20]} )
top <- unique( sub( ".*[.]" , "" , names(unlist(top_all)) ) )

x <- t(sapply(datasets_all_samples[2:3],function(x){
  c(t(x))
}))
colnames(x) <- c(sapply(rownames(datasets_all_samples[[2]]),
                        function(i){rep(i,ncol(datasets_all_samples[[2]]))}))

rownames(x) <- c("Tissue", "Luminal")

top <- sort(sapply( unique(colnames(x)),
               function(i) { mean( x[,colnames(x)==i ] ) } ),decreasing = T)
top <- names(top)[1:30]

###################################
# BACTERIAL ABUNDANCE IN DATASETS #
###################################
par(mar=c(6.5,2.5,0,0)) #b,l,t,r
violist(data = x[,colnames(x)%in%top],
        genes = rownames(x),
        clustering = factor( colnames(x)[colnames(x)%in%top],levels = top) ,
        srt=45, cex.axis=0.7, pt.cex=0.2,  smooth = .1,
        transparency=50,col = pal)
```

### Paulos code with tidyverse
```{r New_files, fig.asp=.5}
Lum <- datasets_all_samples_[[1]][rownames(datasets_all_samples_[[1]])%in%top,]
Tis <- datasets_all_samples_[[2]][rownames(datasets_all_samples_[[1]])%in%top,]

x_Lum <- Lum %>% as_tibble(., rownames ="tax") %>%
  pivot_longer(cols = -tax, names_to = 'ID') #%>% 
  #pivot_wider(names_from = tax, values_from = value)

x_Tis <- Tis %>% as_tibble(., rownames ="tax") %>%
  pivot_longer(cols = -tax, names_to = 'ID') #%>% 
  #pivot_wider(names_from = tax, values_from = value)

xx <- x_Lum %>% left_join(x_Tis, by=c("tax","ID")) %>% select(-ID)
xx_ <- xx %>% filter(!(is.na(.$value.y))) # filter out NA from Tissue

Luminal <- set_names(xx$value.x, xx$tax)
Tissue <- set_names(xx_$value.y, xx_$tax) 

t <- rbind(Tissue, Luminal)

###################################
# BACTERIAL ABUNDANCE IN DATASETS #
###################################
par(mar=c(6.5,2.5,0,0)) #b,l,t,r
violist(data = t, smooth = .1,
        genes = c("Tissue", "Luminal"),
        clustering = factor( colnames(t),levels = top),
        srt=45, cex.axis=0.7, pt.cex=0.2,
        transparency = 50,col = pal)
```

I belive that the reson for the diference seen in the tissue distribution is that some of the samples was removed later on.